apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: liberty-rest-dev

resources:
- namespace.yaml

patchesStrategicMerge:
- pipeline-resource-liberty-rest-app.yaml

bases:
- ../../base
