apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: liberty-rest-app
spec:
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/liberty-rest-dev/liberty-rest-app
  type: image
